version: "3.8"

services:
  # Go Backend API
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-vault-api
    environment:
      # Blockchain Configuration (update these with your actual values)
      ETH_RPC_URL: http://host.docker.internal:8545
      PRIVATE_KEY: your_private_key_here
      VAULT_MANAGER_ADDRESS: 0x...

      # Server Configuration
      SERVER_PORT: 8080
      LOG_LEVEL: info
    ports:
      - "8080:8080"
    networks:
      - ai-vault-network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8080/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  ai-vault-network:
    driver: bridge
